### ISSUE TITLE
Upgrade node redis from v2.* to v4.*

### ISSUE THREAD

**Issue by KiranI-Bsw** [bee-queue/bee-queue#481]
I am using node redis v4.0.2 for my project. However, bee-queue uses v2.* and I am unable to reuse my redis client from v4. Gives somethig like this. I am not dropping out of v4 bcoz I can use promises with node redis itself. Due to this issue I have to open a new connection for bee-queue queue whereas I should have been able to use one. Any suggestion on how to deal with this?

```
node_modules/bee-queue/node_modules/redis/lib/utils.js:65
            var snake_case = elem.replace(/[A-Z][^A-Z]/g, '_$&').toLowerCase();
                                  ^

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:65:35)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:71:32)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:71:32)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:71:32)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:71:32)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:71:32)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:71:32)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:71:32)
    at clone (/Users/bswmac013/Documents/GitHub/redis-matchmaking/matchmaker-consumer/node_modules/bee-queue/node_modules/redis/lib/utils.js:71:32)

```

**Comment by acSpock** [comment]
I am running into this same issue @KiranI-Bsw . I'm looking to figure out a solution before we decide to move to google pubsub. I'll let you know what I find.

**Comment by KiranI-Bsw** [comment]
I've notice that the constructor name for redis client is actually `Commander`. I am new to nodejs ecosystem so do you have any workaround or solution for this?

```
function isClient(object) {
    if (!object || typeof object !== 'object') return false;
    const name = object.constructor.name;
    return name === 'Redis' || name === 'RedisClient';
}
```

Upon researchig around, I believe that lot of things would be simplified (or entirely eliminited) by using v4.

For now setting `sendEvents` and `activateDelayedJobs` to `false` in producer helps with reusing the connection but doesn't work with consumer.

@acSpock Have you found anything?

**Comment by avin-kavish** [comment]
I want this too. But it looks like the package is not being maintained anymore.

**Comment by compwright** [comment]
@avin-kavish @KiranI-Bsw @acSpock I've come on recently as a new member of the maintainers team (and we'd like more if anyone is interested). This is high on the list to do next, FYI.

**Comment by sebaplaza** [comment]
This lib seems to be completely abandoned.

**Comment by pSnehanshu** [comment]
I wanted to use bull, but the job name thing is totally stopping me.

**Comment by romualdr** [comment]
@pSnehanshu I believe BullMQ (which is the successor of Bull) doesn't use name.

**Comment by pSnehanshu** [comment]
@romualdr BullMQ still has names.

**Comment by manast** [comment]
> I wanted to use bull, but the job name thing is totally stopping me.

What is the "job name thing" specifically that is stopping you from using it?

**Comment by repairman29** [comment]
🎯 **PING RECEIVED!**

**@repairman29** has claimed this bounty via [Echeo](https://echeo.io).

**Match Score:** 85%  
**Status:** Ready to start working!

[View conversation in Echeo](https://echeo.io/messages) to coordinate.

**Comment by repairman29** [comment]
Hi! I'm interested in helping with this issue. 

I have experience with index (repairman29/ai-gm-service) and think I can contribute here. Would love to discuss the approach and see if we can make this happen.

*(Connected via [Echeo](https://echeo.io) - a platform for matching developers with open source bounties)*
