### ISSUE TITLE
Allow redis connection lost

### ISSUE THREAD

**Issue by johanlelan** [bee-queue/bee-queue#83]
Can I have a support on connecting/reconnecting my bee-queue to redis server, I try to use a `redis.createClient` instance in vain!

```js
const redis = require('redis');
const Queue = require('bee-queue');
const client = redis.createClient({
  url: process.env.REDIS_URL || 'redis://localhost:6379',
});
const mails = new Queue('mails', {
  redis: client,
  isWorker: false,
});
client.on('end', () => {
  console.log('The mail queue connection has been closed');
});
client.on('connect', () => {
  console.log('The mail queue is connected to the server');
});
mails.on('ready', () => {
  console.log('mail queue now ready to start doing things');
});
```

```
The mail queue is connected to the server
app.js:31
mail queue now ready to start doing things
app.js:35
... TURN OFF REDIS SERVER ...
The mail queue connection has been closed
app.js:27
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
util.js:1021
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
... TURN ON REDIS SERVER ...
```
Is there a configuration way to allow auto-reconnection for `bee-queue`?

Thanks

**Comment by Rush** [comment]
Same question - any strategies for implementing auto-reconnection?

**Comment by LewisJEllis** [comment]
The only recommendation I can make as-is would be to create a new queue instance if the current one's connection fails. That's probably not very reliable though for jobs that had been passed to bee-queue prior to connection failure but had not yet made it to redis...there's probably room for improvement in listening for the redis client's `reconnecting` event and retrying connections.

/cc @skeggse @bradvogel curious how you guys handle this or if it's a major concern for you.

**Comment by bradvogel** [comment]
We haven't handled this. We just log 'error' events - but we haven't seen any in a long time. We're privileged to have a very stable redis connection since we're using AWS Elasticache which is inside our AWS VPC.

**Comment by johanlelan** [comment]
I found a solution with native REDIS options.

```javascript
const redis = require('redis');
const redisOptions = {
  host: process.env.REDIS_HOST || '127.0.0.1',
  port: process.env.REDIS_PORT || 6379,
  db: 0,
  options: {},
  retry_strategy(options) {
    // reconnect after
    return Math.min(options.attempt * 100, 3000);
  },
};

const redisClient = redis.createClient(redisOptions);
let subscriptions;
let processSubscription;

redisClient.on('end', () => {
  debug('REDIS connection has been closed');
});
redisClient.on('error', (err) => {
  error('REDIS client %o', err);
});
redisClient.on('connect', () => {
  debug('REDIS connection is up and running');

  subscriptions = new Queue('subscriptions', {
    redis: redisClient,
    isWorker: false,
    activateDelayedJobs: true,
    removeOnSuccess: true,
  }).on('ready', () => {
    debug('subscriptions queue is ready');
  });

  processSubscription = (options) => {
    const job = subscriptions.createJob(options);
      job.on('failed', (err) => {
        debug('Error on subscription: %o', err);
      });
      return job
        .save()
        .then(() => {
          debug('a set of subscriptions have been saved on job %o', job.id);
          return job;
        });
  };
});
```

**Comment by denigmus** [comment]
Have you done any improvements on that? Bee can't process Redis failure correctly and this is a real problem. It's not about reliability of Redis (e.g. using of AWS), it's just about de-facto for any piece of software correctly process database disconnections.
